### PR TITLE
Recast contribution update proposal.

### PR DESCRIPTION
**Pull request by grasph**
I will send an email.

### CODE REVIEW

**Comment by grasph** [comment]
I've added the missing affiliations. Durham is shared by two authors so I used a label based on the institute instead of the author initials. Maybe we should simply use numbers 1,2,..

**Comment by oliviermattelaer** [comment]
For the affiliations: Fabio and I also share the same. We both use FM for the moment. Would be more consistent to use CP3 instead (to mimick IPPP).

**Comment by grasph** [comment]
Looking at previous Les Houches reports, my understanding is that the affiliations will be on the title page of the report only, and numbers will be used. I expect it was put temporary on the contribution title in order to collect the information and allow contributors to check it. Luca, can you confirm?

**Comment by perrozzi** [comment]
yes I confirm, to the best of my knowledge

**Pull request merged**
